name: CI Pipeline
on:
  pull_request:
    branches:
      - main
      - feature/*
      - bugfix/*
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Install NOde.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: npm install
        working-directory: codebase/rdicidr-0.1.0
      - name: Install prettier globally
        run: npm install -g prettier
      - name: Lint code with ESLint
        run: npm run lint
        working-directory: codebase/rdicidr-0.1.0
      - name: Format code with Prettier
        run: |
          npx prettier --writer "./src/*/.{js,jsx,ts,tsx,json,css,scss,md}"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply automatic formatting changes"
        working-directory: codebase/rdicidr-0.1.0
      - name: Run Tests with Jest
        run: CI=true npm run test
        working-directory: codebase/rdicidr-0.1.0
      - name: Build the Project
        run: npm run build
        working-directory: codebase/rdicidr-0.1.0
      - name: upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: odebase/rdicidr-0.1.0/build/
## cmt##